# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f10827b545119a8354ff4c14acfae6eae7d3da15eb6deea504ae8bdf910551efb904954c83893fe6c156f5caa6fa341c8e1566578348d3c4b99051f4606ba46

test:
  secret_key_base: cae9299f2e550e51d04530fed3f61319083927ea388b8421ad1d31250fad484ae4578087a20586484fe3e1e889bcce1f5c8c5ac558316fc43c0d5017f3a18d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> if Rails.env == 'production'
